"""Gosper flowsnake fill algorithm.

The Gosper curve is a hexagonal space-filling fractal generated by an
L-system. Each iteration replaces every ``A`` and ``B`` in the
production string with their hex-tiling expansions; the resulting
turtle program yields a single continuous polyline that tiles a
hexagonal region. We center + scale the trace per connected component,
clip to the mask, and chunk into per-run polylines — same contract as
:mod:`hilbert`. The visual texture is more organic than Hilbert,
which can be aesthetically preferable for portraits.
"""

from __future__ import annotations

import math
from typing import Any, ClassVar
from xml.sax.saxutils import quoteattr

import numpy as np
from numpy.typing import NDArray

from pen_plotter.converters.algorithms._style import (
    floored_spacing,
    stroke_attr_px,
    tone_darkness,
)
from pen_plotter.converters.algorithms.base import OptionSpec, RasterAlgorithm

_RULES = {
    "A": "A-B--B+A++AA+B-",
    "B": "+A-BB--B-A++A+B",
}


def _expand(axiom: str, depth: int) -> str:
    """Iteratively expand the L-system axiom ``depth`` times."""
    s = axiom
    for _ in range(depth):
        s = "".join(_RULES.get(ch, ch) for ch in s)
    return s


def _trace(commands: str, *, step: float, angle_deg: float = 60.0) -> NDArray[np.float64]:
    """Turtle-interpret the expanded string into XY coordinates."""
    angle = 0.0
    x = y = 0.0
    pts: list[tuple[float, float]] = [(x, y)]
    step_rad = math.radians(angle_deg)
    for ch in commands:
        if ch in ("A", "B"):
            x += step * math.cos(angle)
            y += step * math.sin(angle)
            pts.append((x, y))
        elif ch == "+":
            angle += step_rad
        elif ch == "-":
            angle -= step_rad
    return np.asarray(pts, dtype=np.float64)


def _component_polylines(
    mask: NDArray[np.bool_],
    *,
    spacing_px: float,
    order: int,
    rotation_deg: float,
    keep: NDArray[np.bool_] | None = None,
) -> list[list[tuple[float, float]]]:
    try:
        from scipy.ndimage import label as nd_label
    except ImportError:
        return []
    components, count = nd_label(mask)
    expanded = _expand("A", order)
    base = _trace(expanded, step=1.0)
    # Rotate the curve in its own coordinate system before fitting.
    if rotation_deg:
        a = math.radians(rotation_deg)
        cos_a, sin_a = math.cos(a), math.sin(a)
        rot = np.array([[cos_a, -sin_a], [sin_a, cos_a]])
        base = base @ rot.T

    polylines: list[list[tuple[float, float]]] = []
    for comp_idx in range(1, count + 1):
        ys, xs = np.where(components == comp_idx)
        if xs.size == 0:
            continue
        x_min, x_max = float(xs.min()), float(xs.max())
        y_min, y_max = float(ys.min()), float(ys.max())
        w = max(1.0, x_max - x_min)
        h = max(1.0, y_max - y_min)
        bw = max(1e-6, float(np.ptp(base[:, 0])))
        bh = max(1e-6, float(np.ptp(base[:, 1])))
        # Choose scale so consecutive turtle steps land near spacing_px,
        # capped so the curve still fits the bbox.
        target_scale = min(w / bw, h / bh)
        scale = min(target_scale, spacing_px)
        if scale <= 0:
            continue
        scaled = base * scale
        # Center on bbox centroid.
        cx = (x_min + x_max) / 2.0
        cy = (y_min + y_max) / 2.0
        sx = scaled[:, 0] + cx - (scaled[:, 0].min() + scaled[:, 0].max()) / 2.0
        sy = scaled[:, 1] + cy - (scaled[:, 1].min() + scaled[:, 1].max()) / 2.0
        ix = np.round(sx).astype(np.intp)
        iy = np.round(sy).astype(np.intp)
        inside = (ix >= 0) & (ix < mask.shape[1]) & (iy >= 0) & (iy < mask.shape[0])
        on_mask = np.zeros_like(inside)
        on_mask[inside] = mask[iy[inside], ix[inside]]
        if keep is not None:
            on_mask[inside] &= keep[iy[inside], ix[inside]]
        run: list[tuple[float, float]] = []
        for k in range(len(on_mask)):
            if on_mask[k]:
                run.append((float(sx[k]), float(sy[k])))
            elif run:
                if len(run) >= 2:
                    polylines.append(run)
                run = []
        if run and len(run) >= 2:
            polylines.append(run)
    return polylines


class GosperFillAlgorithm(RasterAlgorithm):
    """Fills connected components with a Gosper flowsnake stroke."""

    name: ClassVar[str] = "gosper"
    description: ClassVar[str] = (
        "Fill regions with a Gosper flowsnake — organic hexagonal space-filling stroke."
    )
    tone_aware: ClassVar[bool] = True

    options_schema: ClassVar[list[OptionSpec]] = [
        OptionSpec(key="order", label="convert.gosperOrder", type="integer",
                   default=4, min=1, max=6, step=1),
        OptionSpec(key="spacing_mm", label="convert.spacing", type="number",
                   default=1.5, min=0.37, max=11, step=0.1),
        OptionSpec(key="rotation_deg", label="convert.angleDeg", type="number",
                   default=0, min=0, max=360, step=5),
    ]

    def render_layer(
        self,
        mask: NDArray[Any],
        color_hex: str,
        label: str,
        *,
        options: dict[str, Any] | None = None,
    ) -> str:
        opts = options or {}
        order = max(1, min(6, int(opts.get("order", 4))))
        spacing = floored_spacing(max(1.0, float(opts.get("spacing_px", 4.0))), opts)
        rotation = float(opts.get("rotation_deg", 0.0))
        bool_mask = mask.astype(bool)

        group_open = (
            f"<g inkscape:label={quoteattr(label)} stroke={quoteattr(color_hex)} "
            f'fill="none" stroke-width="{stroke_attr_px(opts):.3f}" stroke-linecap="round" '
            f'stroke-linejoin="round">'
        )
        if not bool_mask.any():
            return group_open + "</g>"

        # Tonal shading: the base curve skips the highlights, and a second
        # rotated flowsnake overlays the darkest areas for a two-level
        # density ramp. Without a usable tone map the single full-mask
        # curve renders exactly as before.
        darkness = tone_darkness(bool_mask, opts)
        if darkness is None:
            polys = _component_polylines(
                bool_mask, spacing_px=spacing, order=order, rotation_deg=rotation
            )
        else:
            polys = _component_polylines(
                bool_mask,
                spacing_px=spacing,
                order=order,
                rotation_deg=rotation,
                keep=darkness >= 0.1,
            )
            dark_mask = bool_mask & (darkness >= 0.6)
            if dark_mask.any():
                polys.extend(
                    _component_polylines(
                        dark_mask,
                        spacing_px=spacing,
                        order=order,
                        rotation_deg=rotation + 30.0,
                    )
                )
        parts = []
        for poly in polys:
            pts = " ".join(f"{x:.2f},{y:.2f}" for x, y in poly)
            parts.append(f'<polyline points="{pts}"/>')
        return group_open + "".join(parts) + "</g>"
