"""Penrose-tiling algorithm (P3 rhombi).

Covers the region's bounding box with the aperiodic Penrose P3 tiling,
generated by the classic golden-ratio triangle subdivision (Robinson
triangles over complex coordinates), and keeps the tile edges whose
midpoint lies on-mask. The pattern never repeats — a five-fold quasi-
crystal texture impossible to get from the periodic tilings
(``grid`` / ``brick`` / ``truchet``). ``divisions`` controls tile size:
each extra level shrinks tiles by the golden ratio.
"""

from __future__ import annotations

import cmath
import math
from typing import Any, ClassVar
from xml.sax.saxutils import quoteattr

from numpy.typing import NDArray

from pen_plotter.converters.algorithms._style import stroke_attr_px
from pen_plotter.converters.algorithms.base import OptionSpec, RasterAlgorithm

_PHI = (1 + math.sqrt(5)) / 2


def _subdivide(
    triangles: list[tuple[int, complex, complex, complex]],
) -> list[tuple[int, complex, complex, complex]]:
    """One level of Robinson-triangle subdivision (P3 rules)."""
    out: list[tuple[int, complex, complex, complex]] = []
    for colour, a, b, c in triangles:
        if colour == 0:  # thin rhombus half
            p = a + (b - a) / _PHI
            out.append((0, c, p, b))
            out.append((1, p, c, a))
        else:  # thick rhombus half
            q = b + (a - b) / _PHI
            r = b + (c - b) / _PHI
            out.append((1, r, c, a))
            out.append((1, q, r, b))
            out.append((0, r, q, a))
    return out


class PenroseAlgorithm(RasterAlgorithm):
    """Aperiodic Penrose P3 rhombus tiling clipped to the mask."""

    name: ClassVar[str] = "penrose"
    description: ClassVar[str] = (
        "Penrose tiling — aperiodic five-fold rhombi (P3) clipped to the "
        "region, the quasi-crystal texture."
    )

    options_schema: ClassVar[list[OptionSpec]] = [
        OptionSpec(key="divisions", label="convert.divisions", type="integer",
                   default=6, min=2, max=9, step=1),
    ]

    def render_layer(
        self,
        mask: NDArray[Any],
        color_hex: str,
        label: str,
        *,
        options: dict[str, Any] | None = None,
    ) -> str:
        opts = options or {}
        divisions = max(1, min(9, int(opts.get("divisions", 6))))
        bool_mask = mask.astype(bool)
        height, width = bool_mask.shape

        group_open = (
            f"<g inkscape:label={quoteattr(label)} stroke={quoteattr(color_hex)} "
            f'fill="none" stroke-width="{stroke_attr_px(opts):.3f}" '
            f'stroke-linejoin="round">'
        )
        if not bool_mask.any():
            return group_open + "</g>"

        # Sun seed: ten thin triangles fanned around the canvas centre,
        # radius covering the whole bounding box.
        centre = complex(width / 2.0, height / 2.0)
        radius = math.hypot(width, height) / 2.0 + 1.0
        triangles: list[tuple[int, complex, complex, complex]] = []
        for i in range(10):
            b = centre + radius * cmath.exp(1j * math.pi * (2 * i - 1) / 10)
            c = centre + radius * cmath.exp(1j * math.pi * (2 * i + 1) / 10)
            if i % 2 == 0:
                b, c = c, b  # mirror alternate triangles for matching rules
            triangles.append((0, centre, b, c))
        for _ in range(divisions):
            triangles = _subdivide(triangles)

        # Rhombus edges are the triangle sides a-b and a-c (b-c is the
        # internal mirror seam); dedupe shared edges via a rounded key.
        edges: dict[tuple[int, int, int, int], tuple[complex, complex]] = {}
        for _colour, a, b, c in triangles:
            for p, q in ((a, b), (a, c)):
                key_pts = sorted(
                    ((round(p.real * 4), round(p.imag * 4)),
                     (round(q.real * 4), round(q.imag * 4)))
                )
                edges.setdefault(
                    (key_pts[0][0], key_pts[0][1], key_pts[1][0], key_pts[1][1]),
                    (p, q),
                )

        lines: list[str] = []
        for p, q in edges.values():
            mx = int(round((p.real + q.real) / 2.0))
            my = int(round((p.imag + q.imag) / 2.0))
            if not (0 <= mx < width and 0 <= my < height) or not bool_mask[my, mx]:
                continue
            lines.append(
                f'<line x1="{p.real:.2f}" y1="{p.imag:.2f}" '
                f'x2="{q.real:.2f}" y2="{q.imag:.2f}"/>'
            )
        return group_open + "".join(lines) + "</g>"
